// Code generated by go-swagger; DO NOT EDIT.

package cloud_policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// CreateRuleMixin0Reader is a Reader for the CreateRuleMixin0 structure.
type CreateRuleMixin0Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateRuleMixin0Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateRuleMixin0OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateRuleMixin0BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateRuleMixin0Conflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateRuleMixin0InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /cloud-policies/entities/rules/v1] CreateRuleMixin0", response, response.Code())
	}
}

// NewCreateRuleMixin0OK creates a CreateRuleMixin0OK with default headers values
func NewCreateRuleMixin0OK() *CreateRuleMixin0OK {
	return &CreateRuleMixin0OK{}
}

/*
CreateRuleMixin0OK describes a response with status code 200, with default header values.

OK
*/
type CreateRuleMixin0OK struct {
	Payload *models.CommonCreateRuleResponse
}

// IsSuccess returns true when this create rule mixin0 o k response has a 2xx status code
func (o *CreateRuleMixin0OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create rule mixin0 o k response has a 3xx status code
func (o *CreateRuleMixin0OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create rule mixin0 o k response has a 4xx status code
func (o *CreateRuleMixin0OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this create rule mixin0 o k response has a 5xx status code
func (o *CreateRuleMixin0OK) IsServerError() bool {
	return false
}

// IsCode returns true when this create rule mixin0 o k response a status code equal to that given
func (o *CreateRuleMixin0OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the create rule mixin0 o k response
func (o *CreateRuleMixin0OK) Code() int {
	return 200
}

func (o *CreateRuleMixin0OK) Error() string {
	return fmt.Sprintf("[POST /cloud-policies/entities/rules/v1][%d] createRuleMixin0OK  %+v", 200, o.Payload)
}

func (o *CreateRuleMixin0OK) String() string {
	return fmt.Sprintf("[POST /cloud-policies/entities/rules/v1][%d] createRuleMixin0OK  %+v", 200, o.Payload)
}

func (o *CreateRuleMixin0OK) GetPayload() *models.CommonCreateRuleResponse {
	return o.Payload
}

func (o *CreateRuleMixin0OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonCreateRuleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRuleMixin0BadRequest creates a CreateRuleMixin0BadRequest with default headers values
func NewCreateRuleMixin0BadRequest() *CreateRuleMixin0BadRequest {
	return &CreateRuleMixin0BadRequest{}
}

/*
CreateRuleMixin0BadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateRuleMixin0BadRequest struct {
	Payload *models.CommonCreateRuleResponse
}

// IsSuccess returns true when this create rule mixin0 bad request response has a 2xx status code
func (o *CreateRuleMixin0BadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create rule mixin0 bad request response has a 3xx status code
func (o *CreateRuleMixin0BadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create rule mixin0 bad request response has a 4xx status code
func (o *CreateRuleMixin0BadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create rule mixin0 bad request response has a 5xx status code
func (o *CreateRuleMixin0BadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create rule mixin0 bad request response a status code equal to that given
func (o *CreateRuleMixin0BadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create rule mixin0 bad request response
func (o *CreateRuleMixin0BadRequest) Code() int {
	return 400
}

func (o *CreateRuleMixin0BadRequest) Error() string {
	return fmt.Sprintf("[POST /cloud-policies/entities/rules/v1][%d] createRuleMixin0BadRequest  %+v", 400, o.Payload)
}

func (o *CreateRuleMixin0BadRequest) String() string {
	return fmt.Sprintf("[POST /cloud-policies/entities/rules/v1][%d] createRuleMixin0BadRequest  %+v", 400, o.Payload)
}

func (o *CreateRuleMixin0BadRequest) GetPayload() *models.CommonCreateRuleResponse {
	return o.Payload
}

func (o *CreateRuleMixin0BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonCreateRuleResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRuleMixin0Conflict creates a CreateRuleMixin0Conflict with default headers values
func NewCreateRuleMixin0Conflict() *CreateRuleMixin0Conflict {
	return &CreateRuleMixin0Conflict{}
}

/*
CreateRuleMixin0Conflict describes a response with status code 409, with default header values.

Conflict
*/
type CreateRuleMixin0Conflict struct {
	Payload *models.CommonEntitiesResponse
}

// IsSuccess returns true when this create rule mixin0 conflict response has a 2xx status code
func (o *CreateRuleMixin0Conflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create rule mixin0 conflict response has a 3xx status code
func (o *CreateRuleMixin0Conflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create rule mixin0 conflict response has a 4xx status code
func (o *CreateRuleMixin0Conflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this create rule mixin0 conflict response has a 5xx status code
func (o *CreateRuleMixin0Conflict) IsServerError() bool {
	return false
}

// IsCode returns true when this create rule mixin0 conflict response a status code equal to that given
func (o *CreateRuleMixin0Conflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the create rule mixin0 conflict response
func (o *CreateRuleMixin0Conflict) Code() int {
	return 409
}

func (o *CreateRuleMixin0Conflict) Error() string {
	return fmt.Sprintf("[POST /cloud-policies/entities/rules/v1][%d] createRuleMixin0Conflict  %+v", 409, o.Payload)
}

func (o *CreateRuleMixin0Conflict) String() string {
	return fmt.Sprintf("[POST /cloud-policies/entities/rules/v1][%d] createRuleMixin0Conflict  %+v", 409, o.Payload)
}

func (o *CreateRuleMixin0Conflict) GetPayload() *models.CommonEntitiesResponse {
	return o.Payload
}

func (o *CreateRuleMixin0Conflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonEntitiesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateRuleMixin0InternalServerError creates a CreateRuleMixin0InternalServerError with default headers values
func NewCreateRuleMixin0InternalServerError() *CreateRuleMixin0InternalServerError {
	return &CreateRuleMixin0InternalServerError{}
}

/*
CreateRuleMixin0InternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateRuleMixin0InternalServerError struct {
	Payload *models.CommonEntitiesResponse
}

// IsSuccess returns true when this create rule mixin0 internal server error response has a 2xx status code
func (o *CreateRuleMixin0InternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create rule mixin0 internal server error response has a 3xx status code
func (o *CreateRuleMixin0InternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create rule mixin0 internal server error response has a 4xx status code
func (o *CreateRuleMixin0InternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create rule mixin0 internal server error response has a 5xx status code
func (o *CreateRuleMixin0InternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create rule mixin0 internal server error response a status code equal to that given
func (o *CreateRuleMixin0InternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create rule mixin0 internal server error response
func (o *CreateRuleMixin0InternalServerError) Code() int {
	return 500
}

func (o *CreateRuleMixin0InternalServerError) Error() string {
	return fmt.Sprintf("[POST /cloud-policies/entities/rules/v1][%d] createRuleMixin0InternalServerError  %+v", 500, o.Payload)
}

func (o *CreateRuleMixin0InternalServerError) String() string {
	return fmt.Sprintf("[POST /cloud-policies/entities/rules/v1][%d] createRuleMixin0InternalServerError  %+v", 500, o.Payload)
}

func (o *CreateRuleMixin0InternalServerError) GetPayload() *models.CommonEntitiesResponse {
	return o.Payload
}

func (o *CreateRuleMixin0InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CommonEntitiesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
